"""
Nexus v2.0 - Nmap Wrapper
=========================

Wrapper for Nmap running in Docker.
"""

from typing import List, Dict, Any, Optional
import xml.etree.ElementTree as ET
import json
import logging
from dataclasses import dataclass

from nexus.execution.container import get_container

logger = logging.getLogger(__name__)

@dataclass
class NmapResult:
    command: str
    raw_output: str
    hosts: List[Dict[str, Any]]
    
    def to_dict(self):
        return {
            "command": self.command,
            "hosts": self.hosts
        }

async def run_nmap(
    target: str, 
    ports: str = "top-100", 
    flags: str = "-sV -sC -T4"
) -> NmapResult:
    """
    Run Nmap against a target.
    
    Args:
        target: IP or hostname
        ports: Port range (e.g. "80,443", "1-65535", "top-1000")
        flags: Additional nmap flags
        
    Returns:
        Parsed Nmap result
    """
    container = get_container()
    
    # Ensure nmap is installed
    if not await container.check_tool_installed("nmap"):
        await container.install_tool("nmap")
    
    # Construct command
    output_file = f"nmap_{target.replace('/', '_')}.xml"
    
    port_arg = ""
    if ports == "top-100":
        port_arg = "--top-ports 100"
    elif ports == "top-1000":
        port_arg = "--top-ports 1000"
    elif ports == "all":
        port_arg = "-p-"
    else:
        port_arg = f"-p {ports}"
        
    cmd = f"nmap {flags} {port_arg} -oX {output_file} {target}"
    
    # Execute
    logger.info(f"🚀 Running Nmap: {cmd}")
    result = await container.execute_command(cmd)
    
    # Parse output
    hosts = []
    xml_content = await container.read_file(output_file)
    
    if xml_content:
        hosts = parse_nmap_xml(xml_content)
    else:
        logger.error("❌ No XML output generated by Nmap")
        
    return NmapResult(
        command=cmd,
        raw_output=result["stdout"],
        hosts=hosts
    )

def parse_nmap_xml(xml_content: str) -> List[Dict[str, Any]]:
    """Parse Nmap XML output."""
    hosts = []
    try:
        root = ET.fromstring(xml_content)
        
        for host in root.findall("host"):
            host_data = {
                "ip": "",
                "hostnames": [],
                "ports": []
            }
            
            # IP Address
            addr = host.find("address")
            if addr is not None:
                host_data["ip"] = addr.get("addr")
            
            # Hostnames
            hostnames = host.find("hostnames")
            if hostnames is not None:
                for hn in hostnames.findall("hostname"):
                    host_data["hostnames"].append(hn.get("name"))
            
            # Ports
            ports = host.find("ports")
            if ports is not None:
                for port in ports.findall("port"):
                    port_id = port.get("portid")
                    state = port.find("state").get("state")
                    service = port.find("service")
                    service_name = service.get("name") if service is not None else "unknown"
                    product = service.get("product") if service is not None else ""
                    version = service.get("version") if service is not None else ""
                    
                    if state == "open":
                        host_data["ports"].append({
                            "port": int(port_id),
                            "protocol": port.get("protocol"),
                            "service": service_name,
                            "product": product,
                            "version": version
                        })
            
            if host_data["ip"]:
                hosts.append(host_data)
                
    except Exception as e:
        logger.error(f"XML Parsing error: {e}")
        
    return hosts
